[package]
name = "satch"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of picomatch/micromatch pattern matching"
license = "MIT"
authors = ["ushironoko"]

[lib]
name = "satch"
crate-type = ["lib"]

[dependencies]
