[package]
name = "satch-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
satch = { path = ".." }
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "comparison"
harness = false